// node scripts/export-abi.js  → writes ../frontend/src/lib/chain/abi.ts (run after `hardhat compile`)
const fs = require("fs");
const path = require("path");
const names = { CardCollection: "cardCollectionAbi", PackSale: "packSaleAbi", Marketplace: "marketplaceAbi" };
let out = "// AUTO-GENERATED by contracts/scripts/export-abi.js — do not edit\n";
for (const [c, v] of Object.entries(names)) {
  const art = require(`../artifacts/src/${c}.sol/${c}.json`);
  out += `export const ${v} = ${JSON.stringify(art.abi)} as const\n`;
}
const dest = path.join(__dirname, "../../frontend/src/lib/chain/abi.ts");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log("wrote", dest);
